# Generated by Django 3.1.7 on 2021-06-02 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210602_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companygold',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='companymutual',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='gold',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
